export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REQUEST_ROBOTS_PENDING = 'EQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS = 'EQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED = 'EQUEST_ROBOTS_FAILED';
